### ISSUE TITLE
api_instance.list_snapshot_snapshots Invalid value for `size`

### ISSUE THREAD

**Issue by jbd** [Isilon/isilon_sdk_8_0_python#17]
Hello,

I can't make api_instance.list_snapshot_snapshots work. I've got this error:
```
ValueError: Invalid value for `size`, must be a value less than or equal to `4294967295`
```
with this program:
```
$ cat listsnap.py 
from __future__ import print_function
import time
import os
import sys
from pprint import pprint

import isi_sdk_8_1_1 as isi_sdk
from isi_sdk_8_1_1.rest import ApiException

def print_error(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

def main():
    # Configure HTTP basic authorization: basicAuth
    configuration = isi_sdk.Configuration()
    # configure username and password
    configuration.username = os.getenv("ISI_ONEFS_USER")
    configuration.password = os.getenv("ISI_ONEFS_PASS")
    configuration.host = os.getenv("ISI_ONEFS_HOST")
    
    if not all((configuration.username, configuration.password, configuration.host)):
        print_error("You must provide ISI_ONEFS_USER, ISI_ONEFS_PASS and ISI_ONEFS_HOST environment variable")
        sys.exit(42)
    
    configuration.verify_ssl = os.getenv("ISI_ONEFS_VERIFYSSL")
    
    if not configuration.verify_ssl:
        import urllib3
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    
    # create an instance of the API class
    api_client = isi_sdk.ApiClient(configuration)
    api_instance = isi_sdk.SnapshotApi(api_client)

    print("list_snapshot_snapshots:", api_instance.list_snapshot_snapshots())

main()
```

Full traceback:
```
ISI_ONEFS_USER=x ISI_ONEFS_PASS=x ISI_ONEFS_HOST=https://fqdn:8080 python listsnap.py
Traceback (most recent call last):
  File "listsnap.py", line 37, in <module>
    main()
  File "listsnap.py", line 35, in main
    print("list_snapshot_snapshots:", api_instance.list_snapshot_snapshots())
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/api/snapshot_api.py", line 2711, in list_snapshot_snapshots
    (data) = self.list_snapshot_snapshots_with_http_info(**kwargs)  # noqa: E501
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/api/snapshot_api.py", line 2816, in list_snapshot_snapshots_with_http_info
    collection_formats=collection_formats)
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/api_client.py", line 346, in call_api
    _preload_content, _request_timeout)
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/api_client.py", line 185, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/api_client.py", line 257, in deserialize
    return self.__deserialize(data, response_type)
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/api_client.py", line 296, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/api_client.py", line 671, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/api_client.py", line 274, in __deserialize
    for sub_data in data]
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/api_client.py", line 296, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/api_client.py", line 673, in __deserialize_model
    instance = klass(**kwargs)
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/models/snapshot_snapshot_extended.py", line 107, in __init__
    self.size = size
  File "/tmp/snapusage/env/local/lib/python2.7/site-packages/isi_sdk_8_1_1/models/snapshot_snapshot_extended.py", line 422, in size
    raise ValueError("Invalid value for `size`, must be a value less than or equal to `4294967295`")  # noqa: E501
ValueError: Invalid value for `size`, must be a value less than or equal to `4294967295`
```

Do you have an idea ?

Thank you,

Jean-Baptiste

**Comment by jbd** [comment]
From what I can see, it has been corrected in the Isilon/isilon_sdk project for 8.2.0.
