### ISSUE TITLE
regex fail on supportassist_settings_contact_primary.py while getting details of Support Assist 

### ISSUE THREAD

**Issue by Bhavneet-Sharma** [Isilon/isilon_sdk_8_0_python#67]
While getting details of Support assist, regex `if first_name is not None and not re.search('[\\p{L}\\p{M}*\\-\\.\\\' ]*', first_name):` is failing in **supportassist_settings_contact_primary.py**.

SDK method: https://github.com/Isilon/isilon_sdk_python/blob/Isilon_SDK_v0.3.0/isilon_sdk/isilon_sdk/v9_5_0/docs/SupportassistApi.md#get_supportassist_settings

Executed in following Environments:
- Python 3.10
- Python 3.11
- SDK 0.3.0 in both environments

Full Trackback:

- In Python 3.10 environment: 

> Traceback (most recent call last):
  File "/home/powerscale/support_assist.py", line 20, in <module>
    api_response = api_instance.get_supportassist_settings()
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api/supportassist_api.py", line 541, in get_supportassist_settings
    (data) = self.get_supportassist_settings_with_http_info(**kwargs)  # noqa: E501
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api/supportassist_api.py", line 598, in get_supportassist_settings_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py", line 341, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py", line 185, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py", line 257, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py", line 296, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py", line 671, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py", line 296, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py", line 671, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py", line 296, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/api_client.py", line 673, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/models/supportassist_settings_contact_primary.py", line 62, in __init__
    self.first_name = first_name
  File "/usr/local/lib/python3.10/site-packages/isilon_sdk/v9_5_0/models/supportassist_settings_contact_primary.py", line 124, in first_name
    if first_name is not None and not re.search('[\\p{L}\\p{M}*\\-\\.\\\' ]*', first_name):  # noqa: E501
  File "/usr/local/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
  File "/usr/local/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.10/sre_parse.py", line 555, in _parse
    code1 = _class_escape(source, this)
  File "/usr/local/lib/python3.10/sre_parse.py", line 350, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 1

- In Python 3.11 environment:

> Traceback (most recent call last):
  File "/home/support_assist.py", line 20, in <module>
    api_response = api_instance.get_supportassist_settings()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/api/supportassist_api.py", line 541, in get_supportassist_settings
    (data) = self.get_supportassist_settings_with_http_info(**kwargs)  # noqa: E501
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/api/supportassist_api.py", line 598, in get_supportassist_settings_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/api_client.py", line 341, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/api_client.py", line 185, in __call_api
    return_data = self.deserialize(response_data, response_type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/api_client.py", line 257, in deserialize
    return self.__deserialize(data, response_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/api_client.py", line 296, in __deserialize
    return self.__deserialize_model(data, klass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/api_client.py", line 671, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/api_client.py", line 296, in __deserialize
    return self.__deserialize_model(data, klass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/api_client.py", line 671, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/api_client.py", line 296, in __deserialize
    return self.__deserialize_model(data, klass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/api_client.py", line 673, in __deserialize_model
    instance = klass(**kwargs)
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/models/supportassist_settings_contact_primary.py", line 62, in __init__
    self.first_name = first_name
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/models/supportassist_settings_contact_primary.py", line 123, in first_name
    if first_name is not None and not re.search('[\\p{L}\\p{M}*\\-\\.\\\' ]*', first_name):  # noqa: E501
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 982, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 457, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 570, in _parse
    code1 = _class_escape(source, this)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/re/_parser.py", line 363, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 1

**Comment by mmanwani07** [comment]
Fix is available in isilon sdk v0.3.0.1
