### ISSUE TITLE
get_cluster_version fails if there some of the nodes are down

### ISSUE THREAD

**Issue by tadasgr** [Isilon/isilon_sdk_8_0_python#68]
If there are any nodes down in the cluster get_cluster_version call returns an error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/api/cluster_api.py", line 1665, in get_cluster_version
    (data) = self.get_cluster_version_with_http_info(**kwargs)  # noqa: E501
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/api/cluster_api.py", line 1722, in get_cluster_version_with_http_info
    return self.api_client.call_api(
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/api_client.py", line 341, in call_api
    return self.__call_api(resource_path, method,
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/api_client.py", line 185, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/api_client.py", line 257, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/api_client.py", line 296, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/api_client.py", line 671, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/api_client.py", line 273, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/api_client.py", line 273, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/api_client.py", line 296, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/api_client.py", line 673, in __deserialize_model
    instance = klass(**kwargs)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/models/cluster_version_node.py", line 71, in __init__
    self.build = build
  File "/home/user/.local/share/virtualenvs/project/lib/python3.8/site-packages/isilon_sdk/v9_0_0/models/cluster_version_node.py", line 106, in build
    raise ValueError("Invalid value for `build`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `build`, must not be `None``

**Comment by dhanush03122003** [comment]
Can you check if the same issue is on the latest version link : https://github.com/Isilon/isilon_sdk_python , version : Isilon_SDK_v0.3.0.1 .

**Comment by dhanush03122003** [comment]
Here is the link for latest version : https://pypi.org/project/isilon-sdk/ ,  version : Isilon_SDK_v0.4.0.
