### ISSUE TITLE
Error in validating the path for custom_template field while creating the Event channel

### ISSUE THREAD

**Issue by sachin-apa** [Isilon/isilon_sdk_8_0_python#71]
While creating a event channel, when a path is specified for custom template field it fails with an error as regex is not matching.

Run the script with a below code where custom_template field is given an input as "/ifs/data"
```
parameters = isilon_sdk.v9_5_0.EventChannelParameters(
    address="my.email.com",
    custom_template="/ifs/data"
)

event_channel = isilon_sdk.v9_5_0.EventChannelCreateParams(
    enabled=enabled,
    name=name,
    type=type,
    allowed_nodes=allowed_nodes,
    excluded_nodes=excluded_nodes,
    parameters=parameters
)

try:
      api_response = api_instance.create_event_channel(event_channel)
      pprint(api_response)
except ApiException as e:
      print("Exception when calling EventApi->create_event_channel: %s\n" % e)
```

Actual
Fails with an error as below

```
Traceback (most recent call last):
  File "/home/sachin/collections/tryout/powerscale_scripts/event_channel.py", line 159, in <module>
    parameters = isilon_sdk.v9_5_0.EventChannelParameters(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sachin/.local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/models/event_channel_parameters.py", line 87, in __init__
    self.custom_template = custom_template
    ^^^^^^^^^^^^^^^^^^^^
  File "/home/sachin/.local/lib/python3.11/site-packages/isilon_sdk/v9_5_0/models/event_channel_parameters.py", line 209, in custom_template
    raise ValueError("Invalid value for `custom_template`, must be a follow pattern or equal to `/^((\/[^\/[:cntrl:]]+)(\/?))*$/`")  # noqa: E501
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid value for `custom_template`, must be a follow pattern or equal to `/^((\/[^\/[:cntrl:]]+)(\/?))*$/`
```

Expected

Create event channel as the input "/ifs/data/" is a correct input for the field "custom_template".

**Comment by sachin-apa** [comment]
The Issue is because of the regex used` '^((\/[^\/[:cntrl:]]+)(\/?))*$'`
Python regex library is not recognising [:cntrl:] as control parameters, but is just considering as a regular text matching c t r l and hence the SDK is throwing error.

```
>>> import re
>>> re.search('^((\/[^\/[:cntrl:]]+)(\/?))*$', "/ifs/data" )
>>> re.search('^((\/[^\/[:cntrl:]]+)(\/?))*$', "/]]]]]]/" )
<re.Match object; span=(0, 8), match='/]]]]]]/'>
```
Alternative to [:cntrl:] in python is to use `[\x00-\x1F\x7F]` so the regular expression would be `^((\/[^\x00-\x1F\x7F]+)(\/?))*$`

```
>>> re.search('^((\/[^\x00-\x1F\x7F]+)(\/?))*$', "/]]]]]]/" )
<re.Match object; span=(0, 8), match='/]]]]]]/'>
>>> re.search('^((\/[^\x00-\x1F\x7F]+)(\/?))*$', "/ifs/data" )
<re.Match object; span=(0, 9), match='/ifs/data'>
```

**Comment by Bhavneet-Sharma** [comment]
I encountered the same error while attempting to retrieve the details of the ADS provider using this method: [Isilon SDK v0.3.0.1 AuthApi](^1^). The call fails with the following error:

>### ValueError: Invalid value for `home_directory_template`, must follow a pattern or be equal to `/^((\/[^\/[:cntrl:]]+)(\/?))*$/`.

However, this method works in SDK version 9.1, as referenced [here](^2^).

**Comment by mmanwani07** [comment]
Start using the latest https://github.com/Isilon/isilon_sdk/releases/tag/0.5.0 and comment back if still problem persists.

**Comment by sachin-apa** [comment]
Looks like with a latest version this issues is still not fixed.

**Comment by baoy1** [comment]
Same for [providers_ldap_ldap_item.py](https://github.com/Isilon/isilon_sdk_python/blob/Isilon_SDK_v0.5.0/isilon_sdk/isilon_sdk/v9_5_0/models/providers_ldap_ldap_item.py#L1138)

**Comment by mmanwani07** [comment]
isilon-sdk 0.6.0 use our latest package, issue is fixed.
